// <auto-generated />
using System;
using MangaLibrary.Shared.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaLibrary.Server.Migrations
{
    [DbContext(typeof(MangaContext))]
    partial class MangaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Artist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ID");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Japanese manga artist that usually works as the illustrator in collaboration with a writer. First gained international attention for Hikaru no Go with Yumi Hotta, but is better known for Death Note and Bakuman with Tsugumi Ohba.",
                            Name = "Takeshi Obata"
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Was best known for his acclaimed dark fantasy series Berserk, which began serialization in 1989 and continued until his death in 2021.\n\nIn 2002, Miura received the Award for Excellence at the sixth Tezuka Osamu Cultural Prize.",
                            Name = "Kentaro Miura"
                        },
                        new
                        {
                            ID = 2,
                            Name = "SASAKURA Kou"
                        },
                        new
                        {
                            ID = 3,
                            Description = "'Tsugumi Ohba' is the pen name of a Japanese manga writer, best known for authoring the Death Note manga series with illustrator Takeshi Obata. The duo's second series, Bakuman was also successful with 15 million in circulation.",
                            Name = "Tsugumi Ohba"
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Exciting action sequences take priority and significant conflicts between characters are usually resolved with one's physical power.",
                            Name = "Action"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Whether aiming for a specific goal or just struggling to survive, the main character is thrust into unfamiliar situations or lands and continuously faces unexpected dangers.",
                            Name = "Adventure"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Uplifting the audience with positive emotion takes priority, eliciting laughter, amusement, or general entertainment.",
                            Name = "Comedy"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Self-explanatory name, stories of this genre can be more relaxing and about trying rich and tasty food or be about dynamic, stressful work in the kitchen.",
                            Name = "Cooking"
                        },
                        new
                        {
                            ID = 5,
                            Description = "A theme within the Mystery genre, these stories feature either a detective or amateur investigator working to solve a crime or puzzling event.",
                            Name = "Detective"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Plot-driven stories focused on realistic characters experiencing human struggle.",
                            Name = "Drama"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Magical powers, unnatural creatures, or other unreal elements which cannot be explained by science are prevalent and normal to the setting they exist in.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Creating—and maintaining—a sense of dread in the audience takes priority, eliciting shock, fear, or disgust through atmosphere and frightening scenarios.",
                            Name = "Horror"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Stories about life of Japanese idols.",
                            Name = "Idols"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Protagonist getting transferred into another, unknown world.",
                            Name = "Isekai"
                        },
                        new
                        {
                            ID = 11,
                            Description = "Piloting giant humanoid robots.",
                            Name = "Mecha"
                        },
                        new
                        {
                            ID = 12,
                            Description = "Whether its solving a crime or finding an explanation for a puzzling circumstance, the main cast willingly or reluctantly become investigators who must work to answer the who, what, why, and/or how of the current dilemma.",
                            Name = "Mystery"
                        },
                        new
                        {
                            ID = 13,
                            Description = "Survival after end of the world.",
                            Name = "Post-apocalypse"
                        },
                        new
                        {
                            ID = 14,
                            Description = "Falling in love and struggling to progress towards—or maintain—a romantic relationship take priority, while other subplots either take backseat or are designed to develop the main love story.",
                            Name = "Romance"
                        },
                        new
                        {
                            ID = 15,
                            Description = "Imagined technological advancements or natural settings which are currently unreal in the present day but could be invented, caused, or explained by science in the future.",
                            Name = "Si-Fi"
                        },
                        new
                        {
                            ID = 16,
                            Description = "Slice of Life stories are focused on a seemingly random and mundane period of the main characters' lives.",
                            Name = "Slice of Life"
                        },
                        new
                        {
                            ID = 17,
                            Description = "Training for and participating in a sport take priority, with the goal of furthering one's athletic abilities—either to win a competition or achieve some social standing.",
                            Name = "Sports"
                        },
                        new
                        {
                            ID = 18,
                            Description = "Tough life under constant threat of death.",
                            Name = "Survival"
                        },
                        new
                        {
                            ID = 19,
                            Description = "Heroic fantasy. Subgenre of fantasy characterized by sword-wielding heroes engaged in exciting and violent adventures.",
                            Name = "Sword and Sorcery"
                        },
                        new
                        {
                            ID = 20,
                            Description = "Characterized and defined by the elicit moods, giving their audiences heightened feelings of suspense, excitement, surprise, anticipation and anxiety.",
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.JoinTables.MangaArtist", b =>
                {
                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<int>("MangaID")
                        .HasColumnType("int");

                    b.HasKey("ArtistID", "MangaID");

                    b.HasIndex("MangaID");

                    b.ToTable("MangaArtist");

                    b.HasData(
                        new
                        {
                            ArtistID = 1,
                            MangaID = 3
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.JoinTables.MangaAuthor", b =>
                {
                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<int>("MangaID")
                        .HasColumnType("int");

                    b.HasKey("AuthorID", "MangaID");

                    b.HasIndex("MangaID");

                    b.ToTable("MangaAuthor");

                    b.HasData(
                        new
                        {
                            AuthorID = 1,
                            MangaID = 1
                        },
                        new
                        {
                            AuthorID = 2,
                            MangaID = 2
                        },
                        new
                        {
                            AuthorID = 3,
                            MangaID = 3
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.JoinTables.MangaGenre", b =>
                {
                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("MangaID")
                        .HasColumnType("int");

                    b.HasKey("GenreID", "MangaID");

                    b.HasIndex("MangaID");

                    b.ToTable("MangaGenre");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            MangaID = 1
                        },
                        new
                        {
                            GenreID = 8,
                            MangaID = 1
                        },
                        new
                        {
                            GenreID = 2,
                            MangaID = 1
                        },
                        new
                        {
                            GenreID = 7,
                            MangaID = 1
                        },
                        new
                        {
                            GenreID = 19,
                            MangaID = 1
                        },
                        new
                        {
                            GenreID = 1,
                            MangaID = 2
                        },
                        new
                        {
                            GenreID = 6,
                            MangaID = 2
                        },
                        new
                        {
                            GenreID = 7,
                            MangaID = 2
                        },
                        new
                        {
                            GenreID = 1,
                            MangaID = 3
                        },
                        new
                        {
                            GenreID = 6,
                            MangaID = 3
                        },
                        new
                        {
                            GenreID = 5,
                            MangaID = 3
                        },
                        new
                        {
                            GenreID = 20,
                            MangaID = 3
                        },
                        new
                        {
                            GenreID = 1,
                            MangaID = 4
                        },
                        new
                        {
                            GenreID = 6,
                            MangaID = 4
                        },
                        new
                        {
                            GenreID = 13,
                            MangaID = 4
                        },
                        new
                        {
                            GenreID = 8,
                            MangaID = 4
                        },
                        new
                        {
                            GenreID = 1,
                            MangaID = 5
                        },
                        new
                        {
                            GenreID = 6,
                            MangaID = 5
                        },
                        new
                        {
                            GenreID = 14,
                            MangaID = 5
                        },
                        new
                        {
                            GenreID = 8,
                            MangaID = 5
                        },
                        new
                        {
                            GenreID = 7,
                            MangaID = 5
                        },
                        new
                        {
                            GenreID = 1,
                            MangaID = 6
                        },
                        new
                        {
                            GenreID = 3,
                            MangaID = 6
                        },
                        new
                        {
                            GenreID = 14,
                            MangaID = 6
                        },
                        new
                        {
                            GenreID = 7,
                            MangaID = 6
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.JoinTables.MangaPublishing", b =>
                {
                    b.Property<int>("MangaID")
                        .HasColumnType("int");

                    b.Property<int>("PublishingID")
                        .HasColumnType("int");

                    b.HasKey("MangaID", "PublishingID");

                    b.HasIndex("PublishingID");

                    b.ToTable("MangaPublishing");

                    b.HasData(
                        new
                        {
                            MangaID = 1,
                            PublishingID = 1
                        },
                        new
                        {
                            MangaID = 1,
                            PublishingID = 2
                        },
                        new
                        {
                            MangaID = 1,
                            PublishingID = 3
                        },
                        new
                        {
                            MangaID = 2,
                            PublishingID = 4
                        },
                        new
                        {
                            MangaID = 3,
                            PublishingID = 5
                        },
                        new
                        {
                            MangaID = 3,
                            PublishingID = 6
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.JoinTables.MangaTag", b =>
                {
                    b.Property<int>("MangaID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("MangaID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("MangaTag");

                    b.HasData(
                        new
                        {
                            MangaID = 1,
                            TagID = 9
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 20
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 7
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 51
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 31
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 40
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 30
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 48
                        },
                        new
                        {
                            MangaID = 2,
                            TagID = 35
                        },
                        new
                        {
                            MangaID = 2,
                            TagID = 50
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 40
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 35
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 48
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 19
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 7
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 30
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 6
                        },
                        new
                        {
                            MangaID = 4,
                            TagID = 40
                        },
                        new
                        {
                            MangaID = 4,
                            TagID = 39
                        },
                        new
                        {
                            MangaID = 4,
                            TagID = 7
                        },
                        new
                        {
                            MangaID = 4,
                            TagID = 47
                        },
                        new
                        {
                            MangaID = 4,
                            TagID = 51
                        },
                        new
                        {
                            MangaID = 4,
                            TagID = 30
                        },
                        new
                        {
                            MangaID = 4,
                            TagID = 20
                        },
                        new
                        {
                            MangaID = 5,
                            TagID = 40
                        },
                        new
                        {
                            MangaID = 5,
                            TagID = 7
                        },
                        new
                        {
                            MangaID = 5,
                            TagID = 30
                        },
                        new
                        {
                            MangaID = 5,
                            TagID = 20
                        },
                        new
                        {
                            MangaID = 6,
                            TagID = 48
                        },
                        new
                        {
                            MangaID = 6,
                            TagID = 7
                        },
                        new
                        {
                            MangaID = 6,
                            TagID = 30
                        },
                        new
                        {
                            MangaID = 6,
                            TagID = 20
                        },
                        new
                        {
                            MangaID = 6,
                            TagID = 57
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Manga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Mangas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Poster = "https://comicvine.gamespot.com/a/uploads/scale_large/6/67663/5971776-01.jpg",
                            Rating = 5f
                        },
                        new
                        {
                            ID = 2,
                            Poster = "https://comicvine.gamespot.com/a/uploads/scale_large/6/67663/1843338-01.jpg",
                            Rating = 3.3f
                        },
                        new
                        {
                            ID = 3,
                            Poster = "https://comicvine.gamespot.com/a/uploads/scale_large/13/136525/5233385-1.jpg",
                            Rating = 4.8f
                        },
                        new
                        {
                            ID = 4,
                            Poster = "https://comicvine.gamespot.com/a/uploads/scale_large/6/67663/4695905-01.jpg",
                            Rating = 4.9f
                        },
                        new
                        {
                            ID = 5,
                            Poster = "https://comicvine.gamespot.com/a/uploads/scale_large/6/67663/4454598-01.jpg",
                            Rating = 4.2f
                        },
                        new
                        {
                            ID = 6,
                            Poster = "https://comicvine.gamespot.com/a/uploads/scale_large/6/67663/6818656-01.jpg",
                            Rating = 4.7f
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Publishing", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Publishings");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Mainly publishes manga magazines and is involved in series' productions in their games, original video animation, music, and their animated TV series.\n\nThe company is a wholly owned subsidiary of the Hitotsubashi Group.",
                            Name = "Hakusensha",
                            URL = "https://www.hakusensha.co.jp/"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Comic book, graphic novel, and manga publisher founded in Milwaukie, Oregon by Mike Richardson in 1986.\n\nThe company was created using funds earned from Richardson's chain of Portland, Oregon, comic book shops known as Pegasus Books and founded in 1980.",
                            Name = "Dark Horse Comics",
                            URL = "http://www.darkhorse.com/"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Independent publishing house from St. Petersburg. It started its activity in 2005, releasing licensed anime, and since 2010 it became one of the first publishers to form the official manga market in Russia.",
                            Name = "XL Media",
                            URL = "https://xlm.ru/"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Media Factory, formerly known as 'Media Factory, Inc.', doing business as Media Factory, is a Japanese publisher and brand company of Kadokawa Future Publishing.",
                            Name = "Media Factory"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Headquartered in San Francisco, California, focused on publishing manga, and distribution and licensing Japanese anime, films, and television series.\n\nFounded in 1986 and merged to ShoPro Entertaiment in 2005. Owned by Shogakukan-Shueisha Productions.",
                            Name = "VIZ Media",
                            URL = "https://www.viz.com/"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Largest publishing company in Japan, headquartered in Chiyoda. It was established in 1925 as the entertainment-related publishing division of Japanese publisher Shogakukan. The following year, Shueisha became a separate, independent company.",
                            Name = "Shueisha",
                            URL = "https://www.shueisha.co.jp/"
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ID");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Attempt to purify, mature, and perfect certain materials, like the transmutation of \"base metals\" (e.g., lead) into \"noble metals\" (particularly gold).",
                            Name = "Alchemy"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Whole or partial loss of memory.",
                            Name = "Amnesia"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Usually shaped like humans of extraordinary beauty, often identified with bird wings, halos, and divine light.",
                            Name = "Angels"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Anthropomorphs: non-human creatures attributed with human traits and emotions.",
                            Name = "Anthropomorphic"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Half-humans & half-animals.",
                            Name = "Demi Human"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Coercion using the threat of revealing compromising information about a person to the public.",
                            Name = "Blackmail"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Cold and unforgiving.",
                            Name = "Cruel World"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Dystopian si-fi future that tends to focus on a combination of lowlife and high tech.",
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Evil beings, minions of the devil, often humanoid, often depicted with horns, bat-like wings, and pointy spear-like tail.",
                            Name = "Demons"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Large magical legendary creatures.",
                            Name = "Dragons"
                        },
                        new
                        {
                            ID = 11,
                            Description = "Not the smartest.",
                            Name = "Dumb Protagonist"
                        },
                        new
                        {
                            ID = 12,
                            Description = "Monster filled caves/underground places.",
                            Name = "Dungeon"
                        },
                        new
                        {
                            ID = 13,
                            Description = "Distinctive sign of elves are their pointy ears. Commonly shown as creatures with great beauty.",
                            Name = "Elves"
                        },
                        new
                        {
                            ID = 14,
                            Description = "Political unit made up of several territories and peoples, usually created by conquest and controlled by the center, the metropole of the empire.",
                            Name = "Empires"
                        },
                        new
                        {
                            ID = 15,
                            Description = "Female main character.",
                            Name = "Female Protagonist"
                        },
                        new
                        {
                            ID = 16,
                            Description = "World in the far future.",
                            Name = "Future"
                        },
                        new
                        {
                            ID = 17,
                            Description = "Wagering of money with intent of winning more money, where instances of strategy are discounted.",
                            Name = "Gambling"
                        },
                        new
                        {
                            ID = 18,
                            Description = "Soul or spirit of a dead person or another creature that is able to appear to the living.",
                            Name = "Ghosts"
                        },
                        new
                        {
                            ID = 19,
                            Description = "All-mighty supernatural creature.",
                            Name = "Gods"
                        },
                        new
                        {
                            ID = 20,
                            Description = "Blood and violence.",
                            Name = "Gore"
                        },
                        new
                        {
                            ID = 21,
                            Description = "Japanese subculture, nonconformist or rebelling against Japanese social and aesthetic standards.",
                            Name = "Gyaru"
                        },
                        new
                        {
                            ID = 22,
                            Description = "Bunch of women constantly surrounding the protagonist.",
                            Name = "Harem"
                        },
                        new
                        {
                            ID = 23,
                            Description = "Total withdrawal from society and seeking extreme degrees of social isolation and confinement.",
                            Name = "Hikikomori"
                        },
                        new
                        {
                            ID = 24,
                            Description = "Honorable, noble warrior fully clad in plate armor. Usually armed with sword and shield.",
                            Name = "Knights"
                        },
                        new
                        {
                            ID = 25,
                            Description = "Stands for \"lesbian, gay, bisexual, transgender and queer\"",
                            Name = "LGBTQ"
                        },
                        new
                        {
                            ID = 26,
                            Description = "Italian criminal organization.",
                            Name = "Mafia"
                        },
                        new
                        {
                            ID = 27,
                            Description = "People with ability to use magic.",
                            Name = "Mages"
                        },
                        new
                        {
                            ID = 28,
                            Description = "Place where students learn, perfect, or extend their magical powers and knowledge.",
                            Name = "Magic Academy"
                        },
                        new
                        {
                            ID = 29,
                            Description = "Female domestic worker. In manga depicted in style of Victorian era French maids.",
                            Name = "Maids"
                        },
                        new
                        {
                            ID = 30,
                            Description = "Male main character.",
                            Name = "Male Protagonist"
                        },
                        new
                        {
                            ID = 31,
                            Description = "Stories in style of European mediæval period.",
                            Name = "Medieval"
                        },
                        new
                        {
                            ID = 32,
                            Description = "Life as a soldier.",
                            Name = "Military"
                        },
                        new
                        {
                            ID = 33,
                            Description = "Half-girl & half-monster.",
                            Name = "Monstergirls"
                        },
                        new
                        {
                            ID = 34,
                            Description = "Often about life in musical band.",
                            Name = "Music"
                        },
                        new
                        {
                            ID = 35,
                            Description = "Mythical creatures, monsters.",
                            Name = "Mythology"
                        },
                        new
                        {
                            ID = 36,
                            Description = "Japanese assassin.",
                            Name = "Ninja"
                        },
                        new
                        {
                            ID = 37,
                            Description = "Parody of common storytelling tropes.",
                            Name = "Parody"
                        },
                        new
                        {
                            ID = 38,
                            Description = "Sea bandits.",
                            Name = "Pirates"
                        },
                        new
                        {
                            ID = 39,
                            Description = "Power relations among individuals, such as the distribution of resources or status. Sometimes just depiction of political figures.",
                            Name = "Politics"
                        },
                        new
                        {
                            ID = 40,
                            Description = "Mind games, mental anguish, etc.",
                            Name = "Psychological"
                        },
                        new
                        {
                            ID = 41,
                            Description = "Journey toward a specific mission or a goal.",
                            Name = "Quests"
                        },
                        new
                        {
                            ID = 42,
                            Description = "Rebirth in another world after death.",
                            Name = "Reincarnation"
                        },
                        new
                        {
                            ID = 43,
                            Description = "Machine programmable by a computer—capable of carrying out a complex series of actions automatically.",
                            Name = "Robots"
                        },
                        new
                        {
                            ID = 44,
                            Description = "Military nobility, officer caste of medieval Japan, wearing traditional clothes and wielding katanas.",
                            Name = "Samurais"
                        },
                        new
                        {
                            ID = 45,
                            Description = "People being owned and treated like property.",
                            Name = "Slaves"
                        },
                        new
                        {
                            ID = 46,
                            Description = "Rare case.",
                            Name = "Smart Protagonist"
                        },
                        new
                        {
                            ID = 47,
                            Description = "Retrofuturistic aesthetics inspired by 19th-century industrial steam-powered machinery.",
                            Name = "Steampunk"
                        },
                        new
                        {
                            ID = 48,
                            Description = "Primarily taking place on Earth, supernatural stories incorporate elements or attributes that are unnatural and unexplainable by science.",
                            Name = "Supernatural"
                        },
                        new
                        {
                            ID = 49,
                            Description = "Living dead, like zombies or skeletons.",
                            Name = "Undead"
                        },
                        new
                        {
                            ID = 50,
                            Description = "Blood-suckers.",
                            Name = "Vampires"
                        },
                        new
                        {
                            ID = 51,
                            Description = "Story driven around protagonist's desire for retribution.",
                            Name = "Vengeance"
                        },
                        new
                        {
                            ID = 52,
                            Description = "Electronic games.",
                            Name = "Videogames"
                        },
                        new
                        {
                            ID = 53,
                            Description = "Reality but virtual.",
                            Name = "Virtual Reality"
                        },
                        new
                        {
                            ID = 54,
                            Description = "Practitioner of witchcraft: magic used to inflict harm or misfortune on others.",
                            Name = "Witch"
                        },
                        new
                        {
                            ID = 55,
                            Description = "Japanese mafioso.",
                            Name = "Yakuza"
                        },
                        new
                        {
                            ID = 56,
                            Description = "Initially loving and caring until their romantic love, admiration and devotion becomes feisty and mentally destructive in nature through either overprotectiveness, violence, brutality or all three combined.",
                            Name = "Yandere"
                        },
                        new
                        {
                            ID = 57,
                            Description = "Green, undead brain-lover.",
                            Name = "Zombies"
                        });
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.JoinTables.MangaArtist", b =>
                {
                    b.HasOne("MangaLibrary.Shared.Models.Manga.Artist", "Artist")
                        .WithMany("MangaArtists")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaLibrary.Shared.Models.Manga.Manga", "Manga")
                        .WithMany("MangaArtists")
                        .HasForeignKey("MangaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.JoinTables.MangaAuthor", b =>
                {
                    b.HasOne("MangaLibrary.Shared.Models.Manga.Author", "Author")
                        .WithMany("MangaAuthors")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaLibrary.Shared.Models.Manga.Manga", "Manga")
                        .WithMany("MangaAuthors")
                        .HasForeignKey("MangaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.JoinTables.MangaGenre", b =>
                {
                    b.HasOne("MangaLibrary.Shared.Models.Manga.Genre", "Genre")
                        .WithMany("MangaGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaLibrary.Shared.Models.Manga.Manga", "Manga")
                        .WithMany("MangaGenres")
                        .HasForeignKey("MangaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.JoinTables.MangaPublishing", b =>
                {
                    b.HasOne("MangaLibrary.Shared.Models.Manga.Manga", "Manga")
                        .WithMany("MangaPublishings")
                        .HasForeignKey("MangaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaLibrary.Shared.Models.Manga.Publishing", "Publishing")
                        .WithMany("MangaPublishings")
                        .HasForeignKey("PublishingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");

                    b.Navigation("Publishing");
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.JoinTables.MangaTag", b =>
                {
                    b.HasOne("MangaLibrary.Shared.Models.Manga.Manga", "Manga")
                        .WithMany("MangaTags")
                        .HasForeignKey("MangaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaLibrary.Shared.Models.Manga.Tag", "Tag")
                        .WithMany("MangaTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Manga", b =>
                {
                    b.OwnsOne("MangaLibrary.Shared.Models.Manga.MangaDetails", "Details", b1 =>
                        {
                            b1.Property<int>("MangaID")
                                .HasColumnType("int");

                            b1.Property<int>("Bookmarks")
                                .HasColumnType("int");

                            b1.Property<short>("Chapters")
                                .HasColumnType("smallint");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<int>("Favorites")
                                .HasColumnType("int");

                            b1.Property<DateTime>("PublishDate")
                                .HasColumnType("datetime2");

                            b1.Property<short>("ReleaseYear")
                                .HasColumnType("smallint");

                            b1.Property<DateTime>("UpdateDate")
                                .HasColumnType("datetime2");

                            b1.Property<short>("Volumes")
                                .HasColumnType("smallint");

                            b1.HasKey("MangaID");

                            b1.ToTable("Mangas");

                            b1.WithOwner()
                                .HasForeignKey("MangaID");

                            b1.HasData(
                                new
                                {
                                    MangaID = 1,
                                    Bookmarks = 0,
                                    Chapters = (short)376,
                                    Description = "Guts, a former mercenary now known as the \"Black Swordsman\", is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything important to Guts for the purpose of fulfilling his own desires. Now marked for death, Guts becomes condemned to a fate in which he is relentlessly pursued by demonic beings.\n\nSetting out on a dreadful quest riddled with misfortune, Guts, armed with a massive sword and monstrous strength, will let nothing stop him, not even death itself, until he is finally able to take the head of the one who stripped him—and his loved one—of their humanity.",
                                    Favorites = 0,
                                    PublishDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3348),
                                    ReleaseYear = (short)1989,
                                    UpdateDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3321),
                                    Volumes = (short)41
                                },
                                new
                                {
                                    MangaID = 2,
                                    Bookmarks = 0,
                                    Chapters = (short)4,
                                    Description = "\"Akumajō Dracula: Yami no Juin\" had in Japan its own comic series that lasted all of two volumes. The comic series of the same name was created in 2005 by company Mediafactory, and it follows events that overlap with bonus-material comic Prelude of Revenge, whose story was conceived by Ayami Kojima; the series is, according to her, a true extension of the of both Prelude and therein the game's actual story. Adding to its authenticity is the knowledge that Koji Igarashi completely supervised its creation.",
                                    Favorites = 0,
                                    PublishDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3365),
                                    ReleaseYear = (short)2002,
                                    UpdateDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3357),
                                    Volumes = (short)2
                                },
                                new
                                {
                                    MangaID = 3,
                                    Bookmarks = 0,
                                    Chapters = (short)117,
                                    Description = "Ryuk, a god of death, drops his Death Note into the human world for personal pleasure. In Japan, prodigious high school student Light Yagami stumbles upon it. Inside the notebook, he finds a chilling message: those whose names are written in it shall die. Its nonsensical nature amuses Light; but when he tests its power by writing the name of a criminal in it, they suddenly meet their demise.\n\nRealizing the Death Note's vast potential, Light commences a series of nefarious murders under the pseudonym \"Kira\", vowing to cleanse the world of corrupt individuals and create a perfect society where crime ceases to exist. However, the police quickly catch on, and they enlist the help of L—a mastermind detective—to uncover the culprit.\n\nDeath Note tells the thrilling tale of Light and L as they clash in a great battle-of-minds, one that will determine the future of the world.",
                                    Favorites = 0,
                                    PublishDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3383),
                                    ReleaseYear = (short)2003,
                                    UpdateDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3374),
                                    Volumes = (short)12
                                },
                                new
                                {
                                    MangaID = 4,
                                    Bookmarks = 0,
                                    Chapters = (short)139,
                                    Description = "Set in a fantasy world where humanity lives within territories surrounded by three enormous walls that protect them from gigantic man-eating humanoids referred to as Titans The anime follows a group of teenagers living inside cities surrounded by three enormous walls that protect the last vestiges of humanity from gigantic humanoid “Titans” that devour people seemingly for no reason.",
                                    Favorites = 0,
                                    PublishDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3396),
                                    ReleaseYear = (short)2009,
                                    UpdateDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3387),
                                    Volumes = (short)34
                                },
                                new
                                {
                                    MangaID = 5,
                                    Bookmarks = 0,
                                    Chapters = (short)143,
                                    Description = "Shy Ken Kaneki is thrilled to go on a date with the beautiful Rize. But it turns out that she’s only interested in his body—eating it, that is. When a morally questionable rescue transforms him into the first half-human half-Ghoul hybrid, Ken is drawn into the dark and violent world of Ghouls, which exists alongside our own.",
                                    Favorites = 0,
                                    PublishDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3409),
                                    ReleaseYear = (short)2011,
                                    UpdateDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3405),
                                    Volumes = (short)14
                                },
                                new
                                {
                                    MangaID = 6,
                                    Bookmarks = 0,
                                    Chapters = (short)97,
                                    Description = "Denji is desperate to tell the world that he’s Chainsaw Man, but is he competent enough to pull off a proper reveal? Meanwhile, Asa has made a friend! But this new friendship may be hiding a dark secret.",
                                    Favorites = 0,
                                    PublishDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3427),
                                    ReleaseYear = (short)2018,
                                    UpdateDate = new DateTime(2023, 12, 17, 14, 34, 39, 692, DateTimeKind.Local).AddTicks(3418),
                                    Volumes = (short)11
                                });
                        });

                    b.OwnsOne("MangaLibrary.Shared.Models.Manga.Title", "Title", b1 =>
                        {
                            b1.Property<int>("MangaID")
                                .HasColumnType("int");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("Japanese")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("Romaji")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.HasKey("MangaID");

                            b1.ToTable("Mangas");

                            b1.WithOwner()
                                .HasForeignKey("MangaID");

                            b1.HasData(
                                new
                                {
                                    MangaID = 1,
                                    English = "Berserk",
                                    Japanese = "ベルセルク",
                                    Romaji = "Beruseruku"
                                },
                                new
                                {
                                    MangaID = 2,
                                    English = "Castlevania: Curse of Darkness",
                                    Japanese = "悪魔城ドラキュラ 闇の呪印",
                                    Romaji = "Akumajō Dracula: Yami no Juin"
                                },
                                new
                                {
                                    MangaID = 3,
                                    English = "Death Note",
                                    Japanese = "デスノート",
                                    Romaji = "Desu Nōto"
                                },
                                new
                                {
                                    MangaID = 4,
                                    English = "Attack on Titan",
                                    Japanese = "進撃の巨人",
                                    Romaji = "Shingeki no Kyojin"
                                },
                                new
                                {
                                    MangaID = 5,
                                    English = "Tokyo Ghoul",
                                    Japanese = "Tōkyō Gūru",
                                    Romaji = "Desu Nōto"
                                },
                                new
                                {
                                    MangaID = 6,
                                    English = "Chainsaw man",
                                    Japanese = "Chensōman",
                                    Romaji = "Desu Nōto"
                                });
                        });

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Artist", b =>
                {
                    b.Navigation("MangaArtists");
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Author", b =>
                {
                    b.Navigation("MangaAuthors");
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Genre", b =>
                {
                    b.Navigation("MangaGenres");
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Manga", b =>
                {
                    b.Navigation("MangaArtists");

                    b.Navigation("MangaAuthors");

                    b.Navigation("MangaGenres");

                    b.Navigation("MangaPublishings");

                    b.Navigation("MangaTags");
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Publishing", b =>
                {
                    b.Navigation("MangaPublishings");
                });

            modelBuilder.Entity("MangaLibrary.Shared.Models.Manga.Tag", b =>
                {
                    b.Navigation("MangaTags");
                });
#pragma warning restore 612, 618
        }
    }
}
